### ISSUE TITLE
Error while pressing stop button

### ISSUE THREAD

**Issue by moh1122** [IeuanTudurPeace/BleepTest#36]
Hello
The app is crashing when I press stop button and no runner is assigned.
Any clue?

**Comment by IeuanTudurPeace** [comment]
Thanks for informing me! I will have a look at this later today.

**Comment by IeuanTudurPeace** [comment]
I have fixed this issue in [this](https://github.com/IeuanTudurPeace/BleepTest/pull/37) pull request. Thanks again for pointing out the crash 😊
